### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by dheerajbred** [FDX100/cloud-killer#1]
No matter what domain I enter or how I enter it, it keeps asking the same

![image](https://user-images.githubusercontent.com/46578244/75671166-21390b80-5ca4-11ea-92ad-cc0a123a1502.png)

**Comment by FDX100** [comment]
https://www17.animeultima.eu
is not domain name it's url try with
animeultima.eu
and wait to see different ip

**Comment by dheerajbred** [comment]
Thanks for the reply.
I tried with animeultima.eu and with a few other sites. Still the same

![image](https://user-images.githubusercontent.com/46578244/75803913-3184df80-5da5-11ea-8c49-81b7d1ccec70.png)

**Comment by FDX100** [comment]
[+] the domain : www5.animeultima.eu has Ip address by : 104.28.20.127
this is demo version and ,it work perfectly on Linux but for windows it need improve try linux
