### ISSUE TITLE
Useless nonsense

### ISSUE THREAD

**Issue by ethernalsteve** [FDX100/cloud-killer#3]
In English:

God, what is this... It does not use a proxy, it spams packets with ping 😂😂 Just nonsense...
**Translated with google translate**

На Русском:
Боже, что это... Оно не использует прокси, спамит пакеты командой ping 😂😂 Просто чушь...

**Comment by FDX100** [comment]
i think you have to watch codes again . it send get request to those subdomains in the list i set when  ever response is 200 it count it as available then it send ping request to that subdomain to get IPAdress this IPAddress could be that new subdomain without cloudflare protection and server IPAddress is leaked in it . i hope you get it :smile:

**Comment by ethernalsteve** [comment]
And I thought it was "DDoS". Sorry, my friend IDIOT is to blame for everything, who wrote that this is "DDOS", but I did not study the code properly :) The method is not very effective, but it may work

**Translated with google translate**
