### ISSUE TITLE
Shit is not working

### ISSUE THREAD

**Issue by Roboxkin** [FDX100/cloud-killer#4]
[+] enter Target domain >> domain.com
[+] enter Target domain >> domain.com
[+] enter Target domain >> domain.com
[+] enter Target domain >> domain.com
[+] enter Target domain >> domain.com
[+] enter Target domain >> domain.com
[+] enter Target domain >> domain.com
[+] enter Target domain >> domain.com
[+] enter Target domain >> domain.com

**Comment by FDX100** [comment]
fixed
